name: Bug Report
description: Create a report to help us improve Nexios
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting a bug! Please provide the following information to help us address the issue.**

  - type: input
    attributes:
      label: What version of Nexios are you using?
      description: Include the version number or commit hash.
      placeholder: e.g., v0.1.0, commit abc123
      required: true

  - type: input
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: e.g., When I try to run `nexios create`, it fails with an error.
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Include a detailed set of steps to reproduce the bug.
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
      required: true

  - type: input
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: e.g., The command should complete successfully without errors.
      required: true

  - type: input
    attributes:
      label: Actual behavior
      description: What happened instead?
      placeholder: e.g., I received an error message saying "Module not found."
      required: true

  - type: input
    attributes:
      label: Environment
      description: Details about the environment (OS, Python version, etc.)
      placeholder: e.g., Ubuntu 20.04, Python 3.9
      required: true

  - type: input
    attributes:
      label: Additional context
      description: Any other information that might help us diagnose the issue (logs, screenshots, etc.)
      placeholder: e.g., Attach logs or screenshots if necessary.
      required: false
