name: Feature Request
description: Suggest a new idea or feature for Nexios
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for suggesting a feature! Please fill out the following template to help us evaluate your idea.**

  - type: input
    attributes:
      label: What is the feature you would like to see in Nexios?
      description: Provide a clear and concise description of the feature you're requesting.
      placeholder: e.g., I want to be able to integrate Nexios with a specific database.
      required: true

  - type: textarea
    attributes:
      label: Why is this feature important to you?
      description: Describe the problem or pain point this feature will address.
      placeholder: e.g., Currently, I have to manually configure the database integration, which is time-consuming.
      required: true

  - type: input
    attributes:
      label: How would you like this feature to work?
      description: Describe how you envision this feature working or the desired user experience.
      placeholder: e.g., It should allow me to configure the database connection via a simple CLI command.
      required: true

  - type: input
    attributes:
      label: Are there any alternative solutions or workarounds?
      description: Let us know if you have found or are using any alternatives for this feature.
      placeholder: e.g., I use a custom script to handle database configuration.
      required: false

  - type: input
    attributes:
      label: What is your environment?
      description: Information about the system where you want to use this feature (OS, version, etc.)
      placeholder: e.g., Ubuntu 20.04, Python 3.9
      required: true

  - type: input
    attributes:
      label: Additional context
      description: Any other information or context that would help us understand the feature request better.
      placeholder: e.g., Attach mockups or references to similar features in other tools.
      required: false
