name: Release to PyPI

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Set up virtualenv
        run: uv venv
      - name: Install dependencies
        run: uv pip install -e ".[dev]"
      
      - name: Clean Old Builds
        run: rm -rf dist build *.egg-info

      - name: Build package
        run: |
          uv build

      - name: Publish to PyPI with uv
        env:
          PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN_PYPI  }}
        run: |
          uv publish --token $PYPI_TOKEN dist/*

  
